// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltfoumkrgdzduoixkhaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0Zm91bWtyZ2R6ZHVvaXhraGF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1Njg1NTgsImV4cCI6MjA3NjE0NDU1OH0.IcmiUVpLqVHWT6VFr0DBG3JeGvyjLanDpGQ44mjvBxE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});